import React from 'react';
import { Home, Bookmark, Briefcase, Tag, Users, User, Plus, Sparkles, HelpCircle } from 'lucide-react';
import { ActiveTab } from '../types';

interface SidebarProps {
  activeTab: ActiveTab;
  setActiveTab: (tab: ActiveTab) => void;
  onOpenAskModal: () => void;
  savedCount: number;
  isMobileOpen: boolean;
  setIsMobileOpen: (open: boolean) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({
  activeTab,
  setActiveTab,
  onOpenAskModal,
  savedCount,
  isMobileOpen,
  setIsMobileOpen,
}) => {
  const navItems = [
    { id: 'home' as ActiveTab, label: 'Home Feed', icon: Home },
    { id: 'collections' as ActiveTab, label: 'Saved Questions', icon: Bookmark, badge: savedCount > 0 ? savedCount : undefined },
    { id: 'tags' as ActiveTab, label: 'Tags Explorer', icon: Tag },
    { id: 'community' as ActiveTab, label: 'Community & Perks', icon: Users },
    { id: 'find-jobs' as ActiveTab, label: 'Developer Jobs', icon: Briefcase },
    { id: 'profile' as ActiveTab, label: 'My Profile', icon: User },
  ];

  const handleNavClick = (tab: ActiveTab) => {
    setActiveTab(tab);
    setIsMobileOpen(false);
  };

  return (
    <>
      {/* Mobile Backdrop */}
      {isMobileOpen && (
        <div
          className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-30 md:hidden"
          onClick={() => setIsMobileOpen(false)}
        />
      )}

      {/* Sidebar Container */}
      <aside
        className={`fixed md:sticky top-16 left-0 z-30 w-64 h-[calc(100vh-4rem)] bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800 p-4 flex flex-col justify-between transition-transform duration-300 md:translate-x-0 ${
          isMobileOpen ? 'translate-x-0 shadow-2xl' : '-translate-x-full md:translate-x-0'
        }`}
      >
        <div className="space-y-6">
          
          {/* Main Nav Links */}
          <nav className="space-y-1.5" id="sidebar-nav-list">
            <div className="px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
              Menu
            </div>
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = activeTab === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => handleNavClick(item.id)}
                  className={`w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl font-medium text-sm transition-all ${
                    isActive
                      ? 'bg-orange-500/10 text-orange-600 dark:text-orange-400 font-semibold border-l-4 border-orange-500 pl-2.5'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800/80 hover:text-slate-900 dark:hover:text-slate-200'
                  }`}
                  id={`nav-item-${item.id}`}
                >
                  <div className="flex items-center gap-3">
                    <Icon className={`w-4 h-4 ${isActive ? 'text-orange-500' : ''}`} />
                    <span>{item.label}</span>
                  </div>
                  {item.badge !== undefined && (
                    <span className="px-2 py-0.5 text-xs font-bold rounded-full bg-orange-100 dark:bg-orange-950/80 text-orange-600 dark:text-orange-400">
                      {item.badge}
                    </span>
                  )}
                </button>
              );
            })}
          </nav>

          {/* Ask AI Prompt Banner */}
          <div className="p-4 rounded-2xl bg-gradient-to-br from-orange-500/10 via-amber-500/5 to-slate-100 dark:to-slate-800/50 border border-orange-500/20 text-left">
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4 text-orange-500 animate-pulse" />
              <span className="text-xs font-bold text-orange-600 dark:text-orange-400 uppercase tracking-wider">
                DevFlow AI Assistant
              </span>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
              Get instant code explanations, debugging help, and structured answers generated by Gemini models.
            </p>
          </div>
        </div>

        {/* Sidebar Footer Callout */}
        <div className="pt-4 border-t border-slate-200 dark:border-slate-800">
          <button
            onClick={() => {
              onOpenAskModal();
              setIsMobileOpen(false);
            }}
            className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-slate-900 hover:bg-slate-800 dark:bg-slate-100 dark:hover:bg-white text-white dark:text-slate-900 font-semibold text-sm shadow-lg transition-all"
            id="sidebar-ask-btn"
          >
            <Plus className="w-4 h-4" />
            <span>Post a Question</span>
          </button>
        </div>
      </aside>
    </>
  );
};
